x=read.table("len_svtype_reads_qual")
dels = as.matrix(x[x[,2] == "del", c(1,3,4)])
dups = as.matrix(x[x[,2] == "dup", c(1,3,4)])
invs = as.matrix(x[x[,2] == "inv", c(1,3,4)])
trs = as.matrix(x[x[,2] == "tr", c(3,4)])

png("len_vs_reads.png", width=1000, height=1000)
plot(dels[,1], dels[,2], col="red", log = "x", xlab = "Event length", ylab = "Supporting reads")
points(dups[,1], dups[,2], col="green")
points(invs[,1], invs[,2], col="blue")
dev.off()

png("len_vs_reads_zoom.png", width=1000, height=1000)
plot(dels[,1], dels[,2], col="red", log = "x", xlab = "Event length", ylab = "Supporting reads", ylim = c(1, 40))
points(dups[,1], dups[,2], col="green")
points(invs[,1], invs[,2], col="blue")
dev.off()

png("len_vs_qual.png", width=1000, height=1000)
plot(dels[,1], dels[,3], col="red", log = "x", xlab = "Event length", ylab = "Mapping quality")
points(dups[,1], dups[,3], col="green")
points(invs[,1], invs[,3], col="blue")
dev.off()

png("reads_vs_qual.png", width=1000, height=1000)
plot(dels[,2], dels[,3], col="red", xlab = "Supporting reads", ylab = "Mapping quality")
points(dups[,2], dups[,3], col="green")
points(invs[,2], invs[,3], col="blue")
dev.off()

png("reads_vs_qual_zoom.png", width=1000, height=1000)
plot(dels[,2], dels[,3], col="red", xlab = "Supporting reads", ylab = "Mapping quality", xlim = c(1, 40))
points(dups[,2], dups[,3], col="green")
points(invs[,2], invs[,3], col="blue")
dev.off()

quit()

x=read.table("CRC.SV.somatic.NoRepeat.NoDukeExclude.len_svtype2", comment = "#")

png("svlen.png", width=1000, height=1000)
lens = matrix(x[,1])
b = 0.1
d1=density(lens[x[,2] == "del"], bw = b)
d2=density(lens[x[,2] == "dup"], bw = b)
d3=density(lens[x[,2] == "inv"], bw = b)
plot(d1, col = "red", log = "xy")
lines(d2, col = "green")
lines(d3, col = "blue")
dev.off()

x = read.table("CRC.SV.somatic.NoRepeat.NoDukeExclude.svtype_reads", comment = "#")
png("reads.png", width=1000, height=1000)
lens = as.matrix(x[,2])
b = 1
d1=density(lens[x[,1] == "del"], bw = b)
d2=density(lens[x[,1] == "dup"], bw = b)
d3=density(lens[x[,1] == "inv"], bw = b)
plot(d1, col = "red", log = "y")
lines(d2, col = "green")
lines(d3, col = "blue")
dev.off()

x = read.table("CRC.SV.somatic.NoRepeat.NoDukeExclude.svtype_qual", comment = "#")
png("qual.png", width=1000, height=1000)
lens = as.matrix(x[,2])
b = 1
d1=density(lens[x[,1] == "del"], bw = b)
d2=density(lens[x[,1] == "dup"], bw = b)
d3=density(lens[x[,1] == "inv"], bw = b)
plot(d1, col = "red", log = "y")
lines(d2, col = "green")
lines(d3, col = "blue")
dev.off()
